# Generated by Django 5.0.9 on 2025-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrestrict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedip',
            name='id',
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='ip_address',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
