# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-09 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminrestrict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedip',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allowed_ip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowedip',
            name='edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_allowed_ip', to=settings.AUTH_USER_MODEL),
        ),
    ]
