# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrestrict', '0002_allowedip_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedip',
            name='description',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
